vich_uploader:
    db_driver: orm


    mappings:
        # nom du mapping. Utiliser ce nom pour référencer le champ d'upload dans l'entité.
        avatars:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true